# Generated by Django 4.2.30 on 2026-08-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0009_etlrun_remove_validationrun_mapping_and_more'),
        ('workflows', '0008_remove_workflow_poll_duration_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notifications', to='validations.etlrun'),
        ),
    ]
