# Generated by Django 4.2.30 on 2026-08-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0007_alter_validationresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='records_extracted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='records_loaded',
            field=models.IntegerField(default=0),
        ),
    ]
