# Generated by Django 4.2.30 on 2026-08-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0018_rename_validationrule_etlstep_mapping_batch_size_and_more'),
        ('validations', '0008_validationrun_records_extracted_and_more'),
        ('workflows', '0008_remove_workflow_poll_duration_hours_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValidationRun',
            new_name='ETLRun',
        ),
        migrations.RenameModel(
            old_name='ValidationResult',
            new_name='ETLResult',
        ),
    ]
