# Generated by Django 4.2.30 on 2026-08-25 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0018_rename_validationrule_etlstep_mapping_batch_size_and_more'),
        ('workflows', '0009_alter_emailnotification_run'),
        ('validations', '0009_etlrun_remove_validationrun_mapping_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etlrun',
            options={'ordering': ['-created_at'], 'verbose_name': 'ETL Run'},
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etl_runs', to='mappings.mapping'),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_runs', to='workflows.workflow'),
        ),
    ]
