# Generated by Django 4.2.30 on 2026-08-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0010_alter_etlrun_options_alter_etlrun_mapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlrun',
            name='post_sql_status',
            field=models.CharField(blank=True, help_text='Status of Post-SQL execution', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='pre_sql_status',
            field=models.CharField(blank=True, help_text='Status of Pre-SQL execution', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='records_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='records_inserted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='records_updated',
            field=models.IntegerField(default=0),
        ),
    ]
