# Generated by Django 4.2.30 on 2026-08-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0016_mapping_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='custom_query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='filter_column',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='filter_condition',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='incremental_column',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='incremental_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='load_mode',
            field=models.CharField(choices=[('truncate', 'Truncate Load'), ('incremental', 'Incremental Load')], default='truncate', max_length=20),
        ),
        migrations.AddField(
            model_name='mapping',
            name='query_type',
            field=models.CharField(choices=[('table', 'Table Select'), ('custom_query', 'Custom Query')], default='table', max_length=20),
        ),
    ]
