# Generated by Django 4.2.30 on 2026-08-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0017_mapping_custom_query_mapping_filter_column_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValidationRule',
            new_name='ETLStep',
        ),
        migrations.AddField(
            model_name='mapping',
            name='batch_size',
            field=models.IntegerField(default=10000, help_text='Number of records to fetch and load per batch.'),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='load_mode',
            field=models.CharField(choices=[('truncate', 'Full Load'), ('incremental', 'Incremental Load')], default='truncate', max_length=20),
        ),
    ]
