# Generated by Django 4.2.30 on 2026-08-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0018_rename_validationrule_etlstep_mapping_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='post_sql',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='post_sql_location',
            field=models.CharField(choices=[('source', 'Source'), ('target', 'Target')], default='target', max_length=10),
        ),
        migrations.AddField(
            model_name='mapping',
            name='pre_sql',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='pre_sql_location',
            field=models.CharField(choices=[('source', 'Source'), ('target', 'Target')], default='target', max_length=10),
        ),
        migrations.AddField(
            model_name='mapping',
            name='scd_active_flag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='scd_business_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='scd_effective_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='scd_effective_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='scd_track_columns',
            field=models.TextField(blank=True, help_text='Comma-separated target columns to track for changes', null=True),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='load_mode',
            field=models.CharField(choices=[('truncate', 'Full Load'), ('incremental', 'Incremental Load'), ('scd1', 'SCD Type 1'), ('scd2', 'SCD Type 2')], default='truncate', max_length=20),
        ),
    ]
