# Generated by Django 4.2.30 on 2026-09-01 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0019_mapping_post_sql_mapping_post_sql_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinegroup',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='pipelinegroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='mappings.pipelinegroup'),
        ),
        migrations.AlterField(
            model_name='pipelinegroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinegroup',
            unique_together={('parent', 'name')},
        ),
    ]
